### ISSUE TITLE
add a data export wizard at an exercise series level

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#1107]
Right now, in the series context menu, a course admin can download a zip file containing the last submissions before a deadline of each student for all exercises of that series.

This single link can be expanded into an export wizard which offers more choices to the user such as:
- select which exercises to include
- checkbox to take deadline into account
- option to group by student or by exercise (#1063)
- option to only include last submission or all submissions
- option to not include students without submissions (#1062)

!Make sure the indianio export still works after implementing this!

Potential extensions: 
- allow export as pdf instead of zip (#1105)
- also enable this for students instead of only course admins
- export all submissions of a course
- export all your submissions on Dodona

_[Original issue](https://github.ugent.be/dodona/dodona/issues/1107) by @bmesuere on Wed Jun 19 2019 at 20:29._

**Comment by winniederidder** [comment]
Hoe zag je de extra features precies werken?
allow export as pdf instead of zip (#1105): alle aanwezige files in 1 pdf of opnieuw gegroepeerd? Titels e.d. erin wegschrijven om het bruikbaar te houden? Elke submission als aparte pdf?

also enable this for students instead of only course admins
Welke features mogen zij zien, moet de knop "mijn oplossingen downloaden" dan vervangen worden door de "oplossingen downloaden"-knop die redirect naar series/x/download_solutions?

export all submissions of a course
Hoe moet dit eruitzien? Iets als courses/x/download_solutions met gelijkaardige opties? Knop toevoegen bij de "download_scoresheet kebab?

export all your submissions on Dodona
Waar moet deze knop, moet deze redirecten naar users/x/download_solutions?
