### ISSUE TITLE
new logo referencing rubber duck debugging

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1110]
Just an idea. Consider rubber duck as logo for Dodona. Link with rubber duck debugging. Rubber ducks as gadgets for Dodona promo. Some examples of duck appearances.

![image](https://github.ugent.be/storage/user/6/files/6ed06800-94c9-11e9-9f65-e6384f26aa05)

![image](https://github.ugent.be/storage/user/6/files/7859d000-94c9-11e9-8a4e-4ba2fb17597c)

_[Original issue](https://github.ugent.be/dodona/dodona/issues/1110) by @pdawyndt on Sat Jun 22 2019 at 08:43._

**Comment by pdawyndt** [comment]
Here's how it looks like with the material design duck icon

![image](https://user-images.githubusercontent.com/5736113/67158265-39803d80-f336-11e9-8e3a-44eb192b84ae.png)

**Comment by beardhatcode** [comment]
I do not this the rubber duck is an appropriate logo for Dodona. Dodona does not really force its students to "force themselves to explain their code, line-by-line, like to a duck". 

In my opinion Dodona is more about learning to code, rather than learning to debug (Dodona does not have a built-in debugger). Although debugging is a vital part of programming, the debugging work is mostly done by teachers implementing proper testcases.

If we really would like a good real logo it might be best to find some designer to design a logo that fits the brand's identity. For now, I like the current logo.
