### ISSUE TITLE
search by institute label finds too many courses

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1118]
According to the institute listing, HoGent has two courses. However, clicking the link yields for hits if searching is done through the institute label. Perhaps courses wirhout a linked institute are always included in the search results.

![image](https://github.ugent.be/storage/user/6/files/27fd1380-9c29-11e9-9ab8-65af8c9ac54e)

_[Original issue](https://github.ugent.be/dodona/dodona/issues/1118) by @pdawyndt on Mon Jul 01 2019 at 17:54._

**Comment by pdawyndt** [comment]
Repeatedly find it confusing to see courses without institution when searching for courses with a particular institution. This design choice doesn't make sense to me.

**Comment by bmesuere** [comment]
I have thought about this a little, but will do some other work in the next weeks. Some ideas I had were

- switch back to a table-like view instead of the cards
- add a "featured course" property to courses (only editable by Zeus) to be able to highlight stand alone courses such as the YouTube exercises by DP, De Programmeurs leerling, etc
- On the all courses page, feature 3 tabs: courses from my institution, featured courses and all courses. Hide the first tab if there aren't any courses in it.
- Do we still add a filter? Pagination? Filter by AY?
- On the copy course page, we can sort the featured courses first
