### ISSUE TITLE
heatmap on course page shows zero items if the course's academic year hasn't started yet

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1203]
Example course statistics: https://dodona.ugent.be/nl/courses/158/statistics/

![image](https://user-images.githubusercontent.com/5736113/63406875-73db6600-c3eb-11e9-8099-da8f2b7ee586.png)

**Comment by charvp** [comment]
Because we decided to let the academic year start on the first of september and to only show the days of the academic year that have passed yet, zero days are shown. (Note that this also causes an error on line 88 of `heatmap.ts`, since zero days were selected to be shown, so `data.length - 1` equals -1.)

We probably want to rethink which days are shown on the course heatmap visualisation? I can't really come up with better options right now, except for maybe extending the acadamic year by a month (in both directions?).

**Comment by pdawyndt** [comment]
@charvp 

Can you check if your updates solve the following two issues observed in Dodona 2.11.6 (currently deployed version)

- [ ] only three days (monday, wednesday, friday) are shown in heatmap (would expect all seven)
- [ ] submission before September 2019 aren't shown in the heatmap

example: https://dodona.ugent.be/en/courses/166/members/7086/

![image](https://user-images.githubusercontent.com/5736113/64127105-aeaca900-cdb0-11e9-83b6-1b9fd07eb966.png)

**Comment by bmesuere** [comment]
The fix for this issue isn't deployed yet and will be part of 3.0.

**Comment by charvp** [comment]
The three days is intended behaviour. The second issue will be fixed in 3.0.
