### ISSUE TITLE
exercises that are being evaluated, are displayed as incorrect

### ISSUE THREAD

**Issue by thepieterdc** [dodona-edu/dodona#1322]
The exercise below contains no previous submissions. While the exercise was being evaluated, the status at the course overview was "Incorrect" (see image below) instead of "Evaluating..."

![image](https://user-images.githubusercontent.com/6131398/65814661-25d53180-e1e5-11e9-82c1-0967d2927a94.png)

**Comment by charvp** [comment]
First look says that the problem is at https://github.com/dodona-edu/dodona/blob/develop/app/models/transient/exercise_summary.rb#L25

As far as I can tell, a simple check that the submission is running or in the queue there should fix this. A PR for this should include tests. I'll take a look later today when I'm no longer on a train.
