### ISSUE TITLE
issues with iframe descriptions

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1370]
- [ ] some students see no exercise description upon first page load (solved after refresh)
- [ ] some students see exercise with white background when in dark mode

![black_and_white](https://user-images.githubusercontent.com/5736113/66311864-c7f4c800-e90f-11e9-803a-dc19a2315659.png)

**Comment by bmesuere** [comment]
For future reference:
The description (and entire iframe) sometimes disappeared in Firefox directly after loading. This only happened in some of the requests (probably because of concurrency).

It turns out that Firefox has a bug where it sometimes behaves strangely when changing the iframe before it's fully loaded (we found some reports of this on stackoverflow).

After reviewing our code, we found that we wrap all iframes in exercise descriptions with a center tag. This effectively modifies the DOM around the iframe, triggering the bug in Firefox.
