### ISSUE TITLE
broken javascript toggling in exercises descriptions

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1502]
Here's a list of exercises in the Python programming repostory, whose descriptions use JavaScript for toggling content. Since exercise descriptions are included in an iframe, these descriptions have been broken in the iframe (not when they are displayed in isolation):

- reeks04:het raadsel van Nob
- reeks04:rorschachtest
- reeks04:Trevanion
- reeks04:valentijn
- reeks06:herschikking
- reeks07:dubbele vrijspraak
- reeks08:code 39
- reeks09:bewoonbare exoplaneten
- reeks09:chemie in poezie
- reeks09:de parsons code
- reeks09:nonsens
- reeks09:plutokiller
- reeks09:rorschachtest
- reeks09:sequentielogo
- reeks10:cowsay
- reeks10:genetische code
- reeks10:massacentrum
- reeks10:rontgendiffractie
- reeks10:sushi

**Comment by bmesuere** [comment]
It seems that you execute javascript through the href which is tricky in (i)frames. If I change the code to an onclick attribute, it does seem to work.

**Comment by rien** [comment]
The reason why the JavaScript in [Code 39](https://dodona.ugent.be/en/courses/172/series/1696/exercises/1186776322/) doesn't work is because we set `target="_parent"` as default for links (so link in descriptions would trigger navigation in the parent). This would cause the `href="javascript:..."` to be executed in the parent window, but this is prevented in iframes.

Adding `target="_self"` to the anchor fixes the issue. In this case:
```html
<a style="margin-top:8px; margin-bottom:8px;" target="_self" href="javascript:(function(){$('#tip01_en').toggle(); })();">here</a>
```
