### ISSUE TITLE
broken images in highlighter

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1525]
![image](https://user-images.githubusercontent.com/5736113/69879132-f74c0380-12c6-11ea-924e-eaadc3f7f2a1.png)

**Comment by pdawyndt** [comment]
This is the case in all exercises that I checked.

**Comment by pdawyndt** [comment]
Must have to do with access to the media folder, because in [this exercise](https://dodona.ugent.be/en/courses/172/series/1694/exercises/2033201011/) the video no longer plays (which is an .mp4 that is embedded from the media folder)

![image](https://user-images.githubusercontent.com/5736113/69879327-6d506a80-12c7-11ea-94b9-6b89f667ab62.png)

**Comment by rien** [comment]
This is caused by #1464, we've moved the translation of `/media` URL's to JavaScript. But somehow the video doesn't change source URL after it has been replaced.

**Comment by pdawyndt** [comment]
Which does not explain why regular images aren't displayed in the highlighter neither.

**Comment by pdawyndt** [comment]
Closing the highlighter doesn't work either!

**Comment by rien** [comment]
This is all the result of the same change.

We perform the URL rewriting of `/media/` URL's to add a token in order that students can copy the link and then `curl` that item locally (thus avoiding the need for authenticating on Dodona, because they are authenticated by the token).

@pdawyndt are the items students should be able to download locally always given in `<a>` elements? Or can you think of other ways you provide a download link?

**Comment by pdawyndt** [comment]
I think they are always given with hyperlinks.
