### ISSUE TITLE
select styling

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1537]
I don't know if the styling of the dropdowns has changed lately, but the current styling with the small "down" arrow that sticks to the right margin does not seem to blend well with the rest of the Dodona UI.

![image](https://user-images.githubusercontent.com/5736113/69911845-c8967000-1421-11ea-95c6-71b6a84c8fa0.png)

Looking at the bootstrap dropdowns, they seem to have much more spacing around the "down" arrow, which looks nicer to me

![image](https://user-images.githubusercontent.com/5736113/69911864-14e1b000-1422-11ea-95c6-8e4f0afc7ac3.png)

**Comment by beardhatcode** [comment]
An other solution that I commonly see for this kind of problem is to set a background image on the `<select>` that looks like a down arrow and use `appearance` to hide the original arrow.

I'm not fond of the bootstrap dropdowns because they require JavaScript to work and do not have native support in mobile browsers.
