### ISSUE TITLE
Heatmap interpolation issue

### ISSUE THREAD

**Issue by ManuDeBuck** [dodona-edu/dodona#1655]
This is a minor layout bug, but the _heatmap_ (especially in dark mode) isn't as clear as probably wanted (see images below). 

![Schermafdruk van 2020-01-22 09-45-09](https://user-images.githubusercontent.com/36775261/72879027-5e50cc00-3cfc-11ea-872d-1a8b91b593ae.png)

![Schermafdruk van 2020-01-22 09-44-51](https://user-images.githubusercontent.com/36775261/72879015-585aeb00-3cfc-11ea-9c82-51a4816d3a55.png)

I think this *may* have something to do with the following lines of code in [heatmap.ts](https://github.com/dodona-edu/dodona/blob/develop/app/assets/javascripts/heatmap.ts).
 
```typescript
const max = Math.max(...data.map(d => d[1]));
const colorRange = d3.scaleSequential(d3.interpolate(lowColor, highColor)).domain([0, max]);
```
and
```typescript
.attr("fill", d => d[1] === 0 ? "" : colorRange(d[1]));
```

Because I had some _wild_ days submitting a lot of excercices (> 150 submissions) and most of the other _normal_ days have < 10 submissions, I think it is the interpolation process causing this issue.

If what I'm saying is correct, a possible solution would be to limit the maximum amount of submissions (also: I think that's what the GitHub heatmap is doing).

**Comment by charvp** [comment]
After some internal discussion, we don't necessarily agree that this is actually an issue. The outlying days where you submitted a lot are clearly shown to be outliers. Because we have a limited colour space to work with, differentiating in days where there were less submissions isn't as easy, but that isn't necessarily more important than showing that there were outlying days.
