### ISSUE TITLE
Exercise info page: possible improvements

### ISSUE THREAD

**Issue by rien** [dodona-edu/dodona#1732]
- [ ] Better display of big numbers (e.g. submission count)
- [ ] Better display of 'courses using this exercise' (the [ISBN](https://dodona.ugent.be/nl/courses/156/series/1763/exercises/174432505/info/) exercises are very crowded)
   - sort by academic year?
   - add some pagination

**Comment by ninewise** [comment]
Apart from sorting by academic year, I'd also put it as the first column (or right after the course name). Long series/course names push it of the screen but you really want to see the course name and year at the same time.

When hovering over a label, the space in between that label and the next is underlined as well (in my browser). (My screenshot program removed the mouse pointer.)

![asdf](https://user-images.githubusercontent.com/994166/75432807-4a2d6980-594f-11ea-8b7f-08a3b7910a31.png)


I really like the multiple solution tabs, btw.

**Comment by pdawyndt** [comment]
- [ ] contact information is a link, but clicking it has no effect
- [ ] remove dot at the end of the `Created` and `Last edited` fields
- [ ] replace "submission count" by "submitted solutions" (or just solutions"); "Ingediende oplossingen" in Dutch; "Submitted solutions"/"Ingediende oplossingen" is also how this statistic is named on the course page
- [ ] avoid using "here" as an anchor for linking to the documentation; sentence can be rephrased as "See [documentation](url) for information about configuring exercises."
- [ ] link to create about information, creates about page at the wrong location in the GitHub repository; the markdown file is created in the parent directory, while it should at least create it in the exercise directory itself; why do we put the markdown file in the root of the exercise directory, and not in the `description` directory where we also put the descriptions and boilerplate?
- [ ] in the "Usage" table, links to courses open in a new tab, but there seems no reason for it
- [ ] I can't say why, but the icon for the info page in the navigation button does not seem to fit with the other icons surrounding it may it's because it's an open circle, where a filled circle with an inserted letter "i" may look better; or to be more consistent, we could use the same "stats" icon as used for courses
- [ ] statistics tiles are not always properly aranged in a grid (may have something to do with the fact that "Programming language" is split into two lines"

![image](https://user-images.githubusercontent.com/5736113/75604770-abcf0e80-5adc-11ea-9887-55d8d0413334.png)

**Comment by pdawyndt** [comment]
The exercise edit page still contains some static information (bottom) that now appears on the exercise info page, and so it may be removed at this point. The only information missing on the info page is the judge, so that information might be added there.

The info page provides the option to update the "about" information of the exercise, while it seems more logical to provide this option for updating on the edit page of the exercise.

If we have an extra information field to put in the grid of statistics tiles, we no longer have a multiple of three stats to show in the grid. As a solution, we could report separately on the stats of the submitted solutions for the exercise:

- number of submitted solutions (in general and/or in this course)
- number of users that submitted a solution (in general and/or in this course)
- number of users that submitted at least one correct solution (in general and/or in this course)
- number of correct submissions (in general and/or in this course), not needed if we have a pie chart as explained below
- pie chart showing the distribution of statuses of all submitted solutions (in general and/or in this course); this could give an idea about the difficulty of the exercise or the time (number of submissions) it takes to get it correct; we might have an analogue pie chart with aggregated info on the user level (e.g. by looking at the latest submission per user)

**Comment by pdawyndt** [comment]
- [ ] option to allow submitting the selected sample solution directly from the exercise info page
- [ ] option to copy the selected sample solution to the clipboard

**Comment by pdawyndt** [comment]
Too much white space between title and tabs

![image](https://user-images.githubusercontent.com/5736113/75605548-218aa880-5ae4-11ea-82d4-adfb52166f9b.png)

**Comment by pdawyndt** [comment]
Instead of not showing the first file from the solutions directory upon page load, we could trim long files when displaying them, which would allow to show the first file by default. Also provide a download button to download the entire file content.
