### ISSUE TITLE
InvalidAuthenticityToken when changing series description via API

### ISSUE THREAD

**Issue by ninewise** [dodona-edu/dodona#1765]
When trying to modify a series description via the API, I'm getting an error message. The server crashes on `An ActionController::InvalidAuthenticityToken occured in series#update` (you've all had the mails). AFAIK, I wouldn't need an authenticity token when using the API.

My exact request:

```sh
token="..."
series="..."
curl -s \
        -H "Accept: application/json" \
        -H "Authorization: $token" \
        --data '_method=patch' \
        --data-urlencode 'series[description]=test' \
        "https://naos.ugent.be/nl/series/$series/"
```

I've also tried this in a more complex manner, taking the authenticity token from a previous request while reusing those cookies:

```sh
token="..."
series="..."
cookie="$(mktemp)"

request() {
        url="$1"
        shift
        curl -s -H "Authorization: $token" "$@" "https://naos.ugent.be/$url"
}

csrf="$(request "series/$series/" --cookie-jar "$cookie" | sed -n 's_.*<meta name="csrf-token" content="\([^"]*\)" />.*_\1_p')"

request "series/$series/" \
        --cookie "$cookie" \
        -H 'Authority: naos.ugent.be' \
        -H 'Origin: https://naos.ugent.be' \
        -H 'Content-Type: application/x-www-form-urlencoded' \
        -H "Referer: https://naos.ugent.be/nl/series/$series/edit/" \
        -H 'Accept-Encoding: gzip, deflate, br' \
        -H 'Accept: application/json' \
        -H 'X-Requested-With: XMLHttpRequest' \
        -H "X-CSRF-Token: $csrf" \
        --data '_method=patch' \
        --data-urlencode "authenticity_token=$csrf" \
        --data-urlencode 'series%5Bdescription%5D=test' \
        --compressed

rm "$cookie"
```

This results in the same error, but more readable, so I'll post it here:

```
ActionController::InvalidAuthenticityToken in SeriesController#update

ActionController::InvalidAuthenticityToken
Extracted source (around line #217):

#215
#216         def handle_unverified_request
*217           raise ActionController::InvalidAuthenticityToken
#218         end
#219       end
#220     end

Extracted source (around line #249):

#247
#248       def handle_unverified_request # :doc:
*249         forgery_protection_strategy.new(self).handle_unverified_request
#250       end
#251
#252       #:nodoc:

Extracted source (around line #255):

#253       # clear run strategies and remove cached variables.
#254       def handle_unverified_request
*255         super # call the default behaviour which resets/nullifies/raises
#256         request.env["devise.skip_storage"] = true
#257         sign_out_all_scopes(false)
#258       end


Rails.root: /home/dodona/rails/releases/20200226102415

Framework Trace
actionpack (6.0.2.1) lib/action_controller/metal/request_forgery_protection.rb:217:in `handle_unverified_request'
actionpack (6.0.2.1) lib/action_controller/metal/request_forgery_protection.rb:249:in `handle_unverified_request'
devise (4.7.1) lib/devise/controllers/helpers.rb:255:in `handle_unverified_request'
actionpack (6.0.2.1) lib/action_controller/metal/request_forgery_protection.rb:244:in `verify_authenticity_token'
activesupport (6.0.2.1) lib/active_support/callbacks.rb:429:in `block in make_lambda'
...

Request parameters
{"_method"=>"patch",
 "authenticity_token"=>"612YeWJb0lcerLHlwzDrz3sPbbQSRszuqGp8DwVEkytoucIKqVTBj7IZ449JtcPZ2NapkzAR0ETm7OPrVBR2EA==",
 "series"=>{"description"=>"test"},
 "id"=>"259"}

Session dump
_csrf_token: "dhf8uqux4+5lV280RwjIKYzfREOd/QN6QDRqAbuG9hA="
session_id: "63e7a2f3a32c1bd33a5cdbaa1970db41"

Env dump
HTTP_ACCEPT: "application/json"
HTTP_ACCEPT_ENCODING: "gzip, deflate, br"
HTTP_ORIGIN: "https://naos.ugent.be"
HTTP_VERSION: "HTTP/1.1"
HTTP_X_CSRF_TOKEN: "612YeWJb0lcerLHlwzDrz3sPbbQSRszuqGp8DwVEkytoucIKqVTBj7IZ449JtcPZ2NapkzAR0ETm7OPrVBR2EA=="
ORIGINAL_SCRIPT_NAME: ""
REMOTE_ADDR: "78.47.31.148"
SERVER_NAME: "naos.ugent.be"
SERVER_PROTOCOL: "HTTP/1.1"

Response headers
None
```

**Comment by thepieterdc** [comment]
This is resolved by adding the following line on top of the `SeriesController`, as has likewise been done for the `create` method in the `SubmissionController`:

```ruby
skip_before_action :verify_authenticity_token, only: [:update]
```

However, in my opinion it would be better to not list the methods, but skip the token verification for any call that is performed using the api, by adding something like this in the `ApplicationController`, since this feels more like a bandaid patch.

```ruby
protect_from_forgery unless: -> { request.format.json? }
```

Opinions @bmesuere @charvp ?

**Comment by charvp** [comment]
Your second option is indeed the direction we were thinking when discussing this issue earlier. I don't know if `request.format.json?` is the right condition, but we definitely want to fix this for all actions.

**Comment by thepieterdc** [comment]
> I don't know if `request.format.json?` is the right condition, but we definitely want to fix this for all actions.

To be clear, my suggestion was **not** to remove every `skip_before_action` line, since this might break existing requests that are not using the API (e.g. creating a submission using the web UI, or fetching media from medusa). I simply wanted to **add** this method to the `ApplicationController` to allow API access.

**Comment by charvp** [comment]
Removing all `skip_before_action` lines is definitely not right, but the ones that skip verification could probably be removed if we solve this correctly in the `ApplicationController`. We'll need to see when this is implemented.

**Comment by thepieterdc** [comment]
@charvp I did not find a proper way of implementing your suggestion, which was skipping the CSRF token in the `look_for_token`-method in the `ApplicationController`. Furthermore, this would also cause strange behaviour if the user were to request API resources in their browser, since this causes cookies to be sent as well, which sets the `current_user` and omits the `look_for_token`-method (cfr. below)
https://github.com/dodona-edu/dodona/blob/45dd7ec288c5794c3599f0f50cff451b546221df/app/controllers/application_controller.rb#L19

My suggestion would simply be to allow all json requests by skipping the callback in the `ApplicationController`:
```ruby
skip_before_action :verify_authenticity_token, if: :remote_request
```

With `remote_request` being
https://github.com/dodona-edu/dodona/blob/45dd7ec288c5794c3599f0f50cff451b546221df/app/controllers/application_controller.rb#L71-L73
