### ISSUE TITLE
Improve course page performance

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#1892]
The median load time of a course page is 1 second. This is more than expected, so it is worth to investigate this.

![image](https://user-images.githubusercontent.com/481872/80136989-d43a2d00-85a2-11ea-9eb3-fd761e75d1a8.png)

The rise of the 95th percentile is due to the (empty) new cache.

**Comment by bmesuere** [comment]
I'm investigating the page load log of https://naos.ugent.be/nl/courses/2/. I will update this comment with the results.
- Completed 200 OK in 1123ms (Views: 941.2ms | ActiveRecord: 167.5ms | Allocations: 621060)
- 293 select queries

The page contains several parts:
- General setup
- The course stats
- The 3 series that are fully loaded
- The skeleton stuff for each of the other series

**Comment by bmesuere** [comment]
General setup

**Comment by bmesuere** [comment]
Course stats

**Comment by bmesuere** [comment]
Fully loaded series

**Comment by bmesuere** [comment]
**Skeleton series**

It takes 7-10 ms per series. This seems acceptable, but for courses with 50 series it quickly amounts to 500 ms.

```
  Rendered series/_series_status.html.erb (Duration: 0.0ms | Allocations: 5)
  Rendered deadlines/_absolute.html.erb (Duration: 0.0ms | Allocations: 5)
  Exercise Load (0.6ms)  SELECT `exercises`.* FROM `exercises` INNER JOIN `series_memberships` ON `exercises`.`id` = `series_memberships`.`exercise_id` WHERE `series_memberships`.`series_id` = 6 ORDER BY `series_memberships`.`order` ASC, `series_memberships`.`id` ASC
  ↪ app/views/series/_series.html.erb:115
   (0.3ms)  SELECT COUNT(*) FROM `exercises` INNER JOIN `series_memberships` ON `exercises`.`id` = `series_memberships`.`exercise_id` WHERE `series_memberships`.`series_id` = 6
  ↪ app/views/series/_series.html.erb:127
  Rendered series/_series.html.erb (Duration: 8.6ms | Allocations: 3611)
```

Possible actions to reduce this:
- Check why 2 queries are executed instead of only one
- Check if this can't be loaded eagerly

**Comment by bmesuere** [comment]
What do you think, @charvp @rien @thepieterdc ?

**Comment by rien** [comment]
I don't know if adding the exercise count to series would gain much. Maybe it's worth looking at view/parial caching (possibly even with cache headers?).

**Comment by bmesuere** [comment]
> I don't know if adding the exercise count to series would gain much. Maybe it's worth looking at view/parial caching (possibly even with cache headers?).

2ms per series, so for large courses up to 100ms. The recommendation I found online is to not cache anything that takes less than 20ms to generate which is not the case here. Storing the count in the database however is "free".

**Comment by rien** [comment]
In that case, sure :)

**Comment by charvp** [comment]
I would first check the impact of removing the `length` query and look for further optimisations after that. Eager loading doesn't seem like a good idea to me, since we don't actually need the exercises. I don't think we can eager load the count. Caching the number of exercises per series in the series table is an option, but doesn't feel right to me, so I would only do this if it has a significant impact.

**Comment by charvp** [comment]
Ok, now that I actually get how the comments work:
* Definitely agree with adding submission_count to the course and caching it (with delayed invalidation).
* Adding a `submission_id` to ExerciseStatus seems fine? Maybe this will need to be polymorphic so we can also link to the relevant ActivityReadStatus if that's required, but that doesn't seem like a problem to me.
 * Reducing the number of fully loaded series on initial page load seems fine, but 1 is not much. Since we need to query the number of exercises anyway for all series, maybe we can make this dynamic like @thepieterdc suggested? Maybe something like loading at least 10 exercises.
 * As I said in my previous comment, I would first try removing the two queries and see where we stand then (especially in combination with all the other optimisations proposed here).
