### ISSUE TITLE
Improper encoding of linter messages

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2050]
On [this feedback page](https://dodona.ugent.be/nl/feedbacks/64494972/) the linter message should read as `if test < low` but has been stripped to `if test`. We should check if this stripping happens by Dodona or by the judge.

![image](https://user-images.githubusercontent.com/5736113/84375469-e702d280-abdf-11ea-8860-96214f6309c8.png)

**Comment by winniederidder** [comment]
The issue does not arise when using 2 numbers, or when using 1 variable at the left side of the comparison.
![numbers](https://user-images.githubusercontent.com/53743234/91556202-9e32fe00-e932-11ea-949f-5ca693ef73f7.png)
It does however arise when using a variable at the right-hand side, which might be an interesting observation.
![one_number](https://user-images.githubusercontent.com/53743234/91556336-d63a4100-e932-11ea-95da-82ce0e5f42c3.png)

**Comment by bmesuere** [comment]
This is a more serious problem than it seems. The textual output of annotations are added to the page as html without html encoding. If an annotation contains a `<`, this creates invalid html. The browser then tries to fix this by eliminating the invalid tag.

There are several options to fix this:
- escape in ruby when constructing the feedback table
- escape the text in the machineAnnotation constructor
- overwrite the get body in machineAnnotation to use innerText instead of html
