### ISSUE TITLE
List exercises on judge page

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2166]
The judge page mentions the total number submissions for this judge (and links to those submissions), but could also mention the total number of exercises for this judge (and link to those exercises).

**Comment by winniederidder** [comment]
The proposed solution is to add a link to activities?judge=Judge which has all the required information.
Requirements for implementing this then are an informative text and some visual guidelines such as where this link should be put on the page.
@bmesuere @rien ?

**Comment by pdawyndt** [comment]
A repository page directly shows a list of all exercises in the repository. This would be an alternative to the link as suggested by @winniederidder.

**Comment by rien** [comment]
Since this page won't be used as much, adding a listing seems overkill. I would add a link to exercises like we do with the submissions
![jx53](https://user-images.githubusercontent.com/3226995/90479815-8dfb7180-e12f-11ea-962b-84fb78f5aded.png)

I see there is no `scope: :by_judge` present in the activity model, so this should also need be added.
