### ISSUE TITLE
Bootstrap expand/collapse makes weird jumps

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2185]
Example: exercise [light work](https://dodona.ugent.be/en/activities/819600301/)

![collapse](https://user-images.githubusercontent.com/5736113/91256553-ebaf3f80-e767-11ea-82dc-f35ab62481f1.gif)

**Comment by bmesuere** [comment]
The expand/collapse changes the height of the inner iframe content. To prevent double scroll bars, we must set the height of the iframe on the parent page manually to exactly match the content height. What you're seeing is the our code dynamically adapting the to the new height, so I would say this is expected behaviour.
