### ISSUE TITLE
Add three star rating to exercises in series

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/dodona#2203]
Now teachers use the description to indicate the difficulty of exercises or differentiate between them. A three star rating would suffice. This is also beneficial for the students because it gives a clear overview of the different kinds of exercises.

The meaning of the stars is up to the teacher, but I added some suggestions:

* :no_stars: : example exercise from theory presentation, ...
* ⭐: basic/easy exercise
* ⭐⭐: moderate/medium exercise, exercise made in class, ...
* ⭐⭐⭐: advanced/hard exercise to prepare for a test, homework, ...

This a mock-up of the series view:
![image](https://user-images.githubusercontent.com/56451049/91822666-61b81880-ec38-11ea-9a9d-e7b679246fc1.png)

When editing series, the star rating can be entered and the order of the exercises can be modified. This is a mock-up of the edit series view:

![image](https://user-images.githubusercontent.com/56451049/91822734-7a283300-ec38-11ea-86aa-f88918290202.png)

**Comment by bmesuere** [comment]
We used to have such stars but the long story short is they didn't work. They were set by the exercise creator as a fixed value while in practice the difficulty was highly dependent on the context and skill of the student. Settings this for each exercise usage instead of fixed value per exercise, as you propose, solves part of that problem.

Our goal, however, is to make an estimation of the difficulty based on the skill level of the individual student (and to automatically suggest a next exercise).

**Comment by BTWS2** [comment]
Indeed, the perceived difficulty of an exercise depends on the course. It should be up to the teacher to decide because (s)he knows the context, and not the exercise creator. The added bonus is that the teacher can decide what the meaning of the stars is, when assigning the star rating. The teacher can estimate how difficult an exercise is for a student in his/her class.

The goal of automatically suggesting the next exercise is even better, but the three star rating would be a nice intermediary solution and would remain useful in a series overview.
