### ISSUE TITLE
Exporting submissions ignores the series

### ISSUE THREAD

**Issue by toonijn** [dodona-edu/dodona#2211]
If i click on "export student submissions" on an "exercise series" it ignores the series and exports all submissions to those exercises.

![Selection_173](https://user-images.githubusercontent.com/9020072/91983064-71645980-ed2b-11ea-8dbe-7d6cd940875c.png)

I get the same exported zip if I generate it from either of those two series.

**Suggestions for fixing**
- If I use the  export-function on a series, only submissions from that series get exported
- or don't let the UI suggest you can export a series

**Comment by pdawyndt** [comment]
Clarification: Based on the UI, @toonijn would believe that students are split over these two series, based on the fact that they submit in one of both series (these are hidden series with two different deadlines, and students are directed to one series or the other).

So the fact that Dodona does not link submissions to series is somewhat hidden behind the UI here.

**Comment by winniederidder** [comment]
Submissions aren't linked to a series, indeed. When using the same exercise multiple times within a course, Dodona does not know in which series a submission happened. We know the course and the exercise id, which is sufficient in most cases. Therefore, if it is a series with unique exercises within a course, the series export works as expected. Changing the UI would thus not solve the issue. 
Why did you choose to make identical series within a course? Maybe this use case can be explored?

**Comment by pdawyndt** [comment]
@winniederidder These two hidden series were created for an online exam that two groups of students in the course were taking simultaneously. But one group could work an extra hour (special exam facilities). The only difference in the series is the deadline. Each group of students was directed to its own series (other series was invisible to them).

Five minutes before the deadline, Dodona shows a message on top of the editor, which warns students that the deadline is approaching. This is crucial during an online exam, as a replacement for an in-class announcement you would otherwise do during an on campus exam ('Five minutes left!").

**Comment by winniederidder** [comment]
Yes I was thinking about this. Is it an option to let them start earlier instead of finishing later?
But for the actual zip, why would you need a different zip? Do you check during grading whether the current student had special facilities, or do you want the zipping here to perform the division for you?

**Comment by pdawyndt** [comment]
To achieve what @tonijn is suggesting (and I don't insist that we should), one approach could be to explicitly link a selection of users to a series (ad hoc selection). This could also give a refinement to the concept of a "visible/hidden series", where the series would then be visible/hidden only for the selection of users linked to the series, and invisible to all other users.

This could also be used to dynamically add/remove users from the selection, e.g. if a student has finished an exam, revoke his access to the exam by removing him/her from the selection. This way, the student could not, for example, leave the exam room, go home and continue the exam from there.

**Comment by toonijn** [comment]
I don't necessarily need two different zips, but the UI suggests I will get them. It's this inconsistency (between UI and what actually happens) that bothers me.

**Comment by bmesuere** [comment]
@toonijn I understand what you mean and that such feature could be useful, but it's not entirely true that the UI hints that you will get 2 different zip files. If you look at your screenshot, you'll see that the class progress is exactly the same for both series. You also never explicitly linked users to a certain series (and only gave some a different link) and there is no overview of "users" within a series. Again, I understand why you might think you did, but the UI never suggests that.

The suggestion of @pdawyndt will also not solve this.

The current implementation is that if you make a submission within a course, we store the course id. As a result, if you solve an exercise once within a course, it will be solved for all occurrences of that exercise in the course. We don't store the series so we don't even know in which of the 2 series in your example the submission was made.

The obvious solution is to (also) store the series id, but unfortunately this complicates many other things. Overall, queries become more complex and because series are quite flexible there are many edge cases to be handled. For example, what happens with the submissions if a user removes an exercise from a series by accident and later adds it again?
