### ISSUE TITLE
Direct link to individual submissions

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2213]
Students find it hard to get access to the URL of one of their submissions (e.g. to ask for specific feedback on that submission). Something like this might solve it.

![image](https://user-images.githubusercontent.com/5736113/92144999-d72e0f80-ee17-11ea-8fb8-525505252759.png)

**Comment by BTWS2** [comment]
Most of the time, students don't see/use that overview of the solutions. They end up on the view where the assignment is visible in combination with output form the student and the expected output. They mostly ask a question about the code they just handed in.
![image](https://user-images.githubusercontent.com/56451049/92147324-46f1c980-ee1b-11ea-8c67-6868bbb72593.png)

I have a few suggestions where to put the icon:
- next to the "paste my code to the clipboard"-icon. This doesn't fit 100% because the submission link, is a link to the results and the code, so it should be somewhere near the tabs.
- the suggestion of Peter, but if chosen, it should be in combination with somewhere else.
- If the student hovers over the green check mark, red lightning or red cross it changes to a chain icon. The disadvantage is that the feature is hidden.
- **my suggestion would be to place it on the left hand side of the text "Submission for {exercise} by {name} in {course}.** This makes sense because the link refers to that submission.
![image](https://user-images.githubusercontent.com/56451049/92148873-73a6e080-ee1d-11ea-9e3c-96abb0c809b1.png)

If the spacing of the icon doesn't match, the icon can also be placed inline, similar to this:
![image](https://user-images.githubusercontent.com/56451049/92148795-58d46c00-ee1d-11ea-851f-41142f7d9dee.png)
 
![image](https://user-images.githubusercontent.com/56451049/92148855-6be73c00-ee1d-11ea-8d06-c59707a819da.png)

When the icon is clicked, the submission link (e.g. https://dodona.ugent.be/en/submissions/???/) should be copied to the clipboard.

**Comment by beardhatcode** [comment]
I think it might be better to just use history.pushState to ensure that the url in the url bar is the submission link when a result is open. Then no extra ui is needed. And the url is in the intuitive place.

**Comment by BTWS2** [comment]
With the activity link (e.g. https://dodona.ugent.be/nl/courses/???/activities/???/), the assignment is still visible above the submission. This is great when a student made a mistake. The student can scroll up and read up on the details of the assignment. @beardhatcode Is this still possible with your suggestion?
![image](https://user-images.githubusercontent.com/56451049/92209984-40506a00-ee8e-11ea-9976-50378b459b3d.png)

The submission link doesn't show the assignment. For the teacher the submission of the student is the most important part, so this doesn't matter that much. The assignment can be opened in a new tab. For students I prefer the activities view.
![image](https://user-images.githubusercontent.com/56451049/92210015-49413b80-ee8e-11ea-91fb-da4588a8e3bc.png)

**Comment by beardhatcode** [comment]
Yes, maybe with a link like `/courses/???/acrtivities/???/submissions/???` but it should be doable, I think. However, there may be even better solutions to this that do not involve UI changes.

**Comment by BTWS2** [comment]
The advantage of a small UI tweak is that students don't need to click on the link at the top, right click, copy or CTRL+C. If a students clicks one more time, the selection is gone and they have to select the URL themselves. For young students a single click in the UI, which copies the link to the clipboard is less cumbersome.

**Comment by beardhatcode** [comment]
Once they have copied the link they will need to be able to paste it anyway. So I don't think that is a problem. 
Selecting the link can indeed be slightly more tricky, but if they fail to click the url once, they can just click the page and try again. Alternatively, they can just drag the url to another window.
![untitled](https://user-images.githubusercontent.com/662538/92216168-40546800-ee96-11ea-9ab5-fc4643dd3f94.gif)

**Comment by BTWS2** [comment]
This assumes young students know how to place two windows side by side. Many students don't even know that Windows has a feature that snaps windows to a side if the window is dragged against it. They use most applications full screen. Dragging via the icon in the taskbar is even harder. Dragging UI elements in an operating system like Windows isn't that common for basic users. The solution should be with as less friction or points of failure as possible.
