### ISSUE TITLE
Code copy and activity icon is the same

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/dodona#2215]
The paste/clipboard icon is used in the UI of creating an API and submitted code, while perhaps the copy icon would be better: https://materialdesignicons.com/icon/content-copy or (https://cdn.materialdesignicons.com/1.1.34/​ (mdi-content-copy))
![image](https://user-images.githubusercontent.com/56451049/92233246-350e3600-eeb0-11ea-853a-c260ab6d7980.png)

![clipboard_api](https://user-images.githubusercontent.com/56451049/92232785-6a665400-eeaf-11ea-8c58-55386876bb17.PNG)

![clipboard_code](https://user-images.githubusercontent.com/56451049/92232781-69352700-eeaf-11ea-9a28-126e63508fb1.PNG)

In Word/Windows it is also used that way.
![clipboard_word](https://user-images.githubusercontent.com/56451049/92232784-69cdbd80-eeaf-11ea-8af7-4b67f5446ad3.PNG)

**Comment by bmesuere** [comment]
When we initially made this icon choice, I've actually done a bit of research. In text editors, where there is a cut/copy/paste option the "2 page" icon is indeed often used. On web applications to copy a one-off field, the clipboard icon seemed more prevalent (e.g. here on GitHub). This makes sense because the "2 page" icon is quite generic and without the additional context of cut/paste it could really be anything. In fact, on Dodona, we use a similar icon to depict multiple submissions.

In addition, there should be a tooltip on every copy button on Dodona.

Therefore, we'll keep the current icon.

**Comment by BTWS2** [comment]
Is it an option to use [this icon](https://material.io/resources/icons/?search=clipboard&icon=content_paste&style=baseline) instead? 
![image](https://user-images.githubusercontent.com/56451049/92238044-b4076c80-eeb8-11ea-86ec-ff58d966c27c.png)

Now the icon for the assignment and copying the code is the same:
![image](https://user-images.githubusercontent.com/56451049/92238070-be296b00-eeb8-11ea-8228-8206af579e40.png)

Then it will be the same as in GitHub:
![image](https://user-images.githubusercontent.com/56451049/92237987-9a662500-eeb8-11ea-9c35-180ca7822046.png)
![image](https://user-images.githubusercontent.com/56451049/92238160-e9ac5580-eeb8-11ea-9cde-70acc6ac6bbc.png)
