### ISSUE TITLE
Wrong date last edited in activity info

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2374]
Activity info mentions the date last edited, but this is how it looks like for an exercises that was edited minutes ago:

![image](https://user-images.githubusercontent.com/5736113/98441516-2259ec80-20ff-11eb-9310-b7c8341347a0.png)

**Comment by rien** [comment]
I guess the edit was in the git repository? This field uses the `updated_at` information in the database, which won't be updated when the git repo changes.

**Comment by pdawyndt** [comment]
Yves, it was in the git repo. Wouldn’t it be more logical is the edit date were also updated in the exercise is modified through the repo?

**Comment by rien** [comment]
It would indeed be more logical, but this would require discovering which files were changed by the repository update. 
We currently only process the `config.json` files to update activities, adding this functionality would be non-trivial and will increase the complexity of an already complex feature.

I suggest adding a clarification to the tooltip, because fixing this doesn't seem worth the effort in my opinion.

**Comment by pdawyndt** [comment]
Maybe remove date last edited if the information given is misleading?
