### ISSUE TITLE
NoMethodError in question policy

### ISSUE THREAD

**Issue by niknetniko** [dodona-edu/dodona#2505]
```
A NoMethodError occurred in annotations#update:

  undefined method `course_admin?' for nil:NilClass
  app/policies/question_policy.rb:19:in `transition?'

```

With the following params:
```ruby
{"from"=>"unanswered", "question"=>{"question_state"=>"answered"}, "controller"=>"annotations", "action"=>"update", "locale"=>"nl", "id"=>"redacted", "format"=>"json", "annotation"=>{}}
```

**Comment by chvp** [comment]
Both issues we saw this morning are caused by someone who is still seeing a page tailored for a course admin despite being logged out (the exceptions still shouldn't happen in that case though). I'm going through the logs, but I haven't been able to find why the person in question was suddenly logged out.
