### ISSUE TITLE
WebMock seems to insert itself in the delayed job runner in development

### ISSUE THREAD

**Issue by chvp** [dodona-edu/dodona#3167]
This makes it so one can't evaluate submissions, since the docker communication is HTTP over a socket, which webmock then breaks.

**Comment by jorg-vr** [comment]
Potential cause:
the line `Bundler.require(*Rails.groups)` (in `application.rb`) seems to include `webmock` even though it is not specified in the `:development` group in `Gemfile`

This in itself could be caused by earlier calls to `bundler` as discussed here: https://github.com/rubygems/rubygems/issues/4915
Yet so far I was unable to solve the bug this way

Adding `WebMock.disable!` in `application.rb` and `WebMock.enable!` in `test_helper.rb` resolves the issue while keeping the tests running successfully

At the moment this solution is not implemented as it just patches the problem without treating the root cause.

**Comment by jorg-vr** [comment]
Not sure if this is relevant but note for further debugging:

Problem appears when running the job server: `bundle exec rails jobs:work`
If `bundle exec rails s -p 3000` is started with `webmock` in the gemfile and  `bundle exec rails jobs:work` is started without `webmock` in the gemfile everything still works (While it does not work the other way around)
