### ISSUE TITLE
Ace editor prevents searching with CTRL+F

### ISSUE THREAD

**Issue by niknetniko** [dodona-edu/dodona#3332]
The ace editor (on the page for creating/editing a submission) captures <kbd>Ctrl</kbd>+<kbd>F</kbd>, but doesn't show a search field or anything. When the cursor is in the editor, it is impossible to search the page.

I believe this is because <kbd>Ctrl</kbd>+<kbd>F</kbd> tries to load the search extension, which we don't have (it tries to load `/assets/ace/ext-searchbox.js:`). See:
![image](https://user-images.githubusercontent.com/1756811/151713936-0a1c0ff5-ad8d-4b20-8d4c-0181874c170e.png)

This is unfortunately apparently unsupported by our gem, see https://github.com/codykrieger/ace-rails-ap/issues/27 and PR https://github.com/codykrieger/ace-rails-ap/pull/38.

**Comment by bmesuere** [comment]
The documentation of the editor is awful. In some code examples, I have found `editor.commands.addCommand` to add custom shortcuts, so maybe there is also a `removeCommand`. The documentation doesn't even list the `commands` property of an editor.

**Comment by bmesuere** [comment]
There seems to be a `removeCommand` [here](https://github.com/ajaxorg/ace/blob/master/lib/ace/keyboard/hash_handler.js#L66). Unfortunately, none of the keybindings in the repository include a find command binding to ctrl/cmd + F. We will probably have to dump the command list from a live example to figure out the name.

**Comment by niknetniko** [comment]
It might be this command:

https://github.com/ajaxorg/ace/blob/8a991ccbc8d4e0f0c26309cb0ef6aa6828d3b549/lib/ace/commands/default_commands.js#L202-L208

**Comment by BramDevlaminck** [comment]
This issue seems to be solved for me. This is how this looks right now:



![Image](https://user-images.githubusercontent.com/68779933/182318347-da32d341-4933-41f4-a893-3b65c37a2656.png)




![Image](https://user-images.githubusercontent.com/68779933/182318416-a2b77b3c-885d-4f06-8131-6ad1544a5bfc.png)


(both when trying to Ctrl-F/Command-F in the editor itself and on the webpage)

**Comment by pdawyndt** [comment]
Same observation as @niknetniko on my Windows-10 machine: works on naos, not on Dodona (release 5.6.5). Console messages in Chrome DevTools:

![image](https://user-images.githubusercontent.com/5736113/182342386-b5f3c272-3792-420c-b7a7-3aef04af324c.png)

Last message appears upon CTRL-F.

**Comment by BramDevlaminck** [comment]
How should I move forward with this? My understanding of this at the moment is that the deployed version is broken, but somehow the local development version works?

**Comment by jorg-vr** [comment]
As I understand it:
- The code mentioned by @niknetniko blocks the global use of ctrl-f
- This code originates in the ace-editor
- This ace-editor code is not loaded correctly in our staging  (naos) and our development environment

The solution for the problem in production is probably finding a way to disable the relevant piece of ace-editor code (Maybe it has a setting so it does not try to import searchbox js at all?)

You probably won't be able to test your solution before we move to production, but if you are reasonably confident it will work and it does not break anything else then we can just roll it out and see if it has worked.

Alternativly you can first try to fix the development environment beviour. (So that it loads all the ace-editor code in the same way as production does)

**Comment by niknetniko** [comment]
The issue is that ace extensions are not included in the release version. A fix upstream exists in a PR (https://github.com/codykrieger/ace-rails-ap/pull/38), but has not been merged yet.

Another solution is to remove the find command, so we just use the browser-provided search, see one of the comments above for the name of the command and the `removeCommand` method.

**Comment by BramDevlaminck** [comment]
I'll look into removing the search option since the last merge in the mentioned ACE repo is already 2 years ago. This makes me believe that it could take a while before the fix is merged.
