### ISSUE TITLE
Only show submissions without a course in the submission overview on the submission detail page

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#3544]
For exercises that have submissions prior to numbering of submissions was introduced, there seems to be an off-by-one error

![image](https://user-images.githubusercontent.com/5736113/163923855-60606077-7b46-44c7-8222-06d931da05da.png)
![image](https://user-images.githubusercontent.com/5736113/163923878-533fe26e-4acc-4447-858e-bb290b0f2b45.png)

**Comment by jorg-vr** [comment]
Odd, still works correctly when I try to reproduce: 
![image](https://user-images.githubusercontent.com/21177904/163949398-19e892e2-4622-4ad6-9b99-5d95fbf87649.png)

Could you link me the specific exercise so I can investigate further?

One potential cause: we number submissions within the context of a course, so it could have happened that 9 submissions happened in the course and 1 happened outside. If this is indeed the cause we should improve the automatically numbered list. (Either by only showing submissions within the same course, or by using the database numbers instead of generated ones)

**Comment by pdawyndt** [comment]
Just happende again in class with this exercise https://dodona.ugent.be/nl/exercises/837426097/. As you’ll see, these submission are not scopes in a course, so that’s probabilistisch where the issue occurs. Nummering should at leaset be the same on the same page (which is where off by onze occurs).

**Comment by pdawyndt** [comment]
Also: wouldn’t it be logical to add numbers to all submissions retroactively?

**Comment by jorg-vr** [comment]
Ok I found the issue.

One submission was made within the context of a course: https://dodona.ugent.be/nl/submissions/7583516/ and thus numbered separately
Here only submissions within the same course are shown as expected

The other submissions were done without a course context. But their submission overview also shows all submissions that have a course, which results in an incorrect numbering:
![image](https://user-images.githubusercontent.com/21177904/163954686-b03dc876-7d44-459f-b782-311500306aa4.png)
