### ISSUE TITLE
Consider double-clicking a comment as a way to update the comment

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#4653]
Updating a comment after it was initially written, is some action I do very often. This used to be a single click when the action could be triggered through its own button, but now requires two clicks as the action now has to be launched from a menu. Maybe we could consider double-clicking a comment as a way to launch the action of updating the comment.

**Comment by jorg-vr** [comment]
Does this double click interaction work on any other major platform? eg. facebook, google docs, github...

Adding an extra click for a feature that is often used is indeed bad practice (I did not realize that edit was used this often)
But i am unsure if this proposed solution is the right one, because we would introduce a UX feature that users are not familiar with.

If  the edit button is indeed as often used, we should just make the button available without the dropdown menu

**Comment by jorg-vr** [comment]
Some statistics:
On naos 5892 out of 54119 annotations of the last two years have been edited after creation, so roughly 10 percent.

I filtered out:
- questions as we would count updates to the question state
- saved annotations: as we would count them being saved after the fact
- annotations more then 2 years old: because the whole table was updated back then
```
Annotation.where(type: "Annotation", created_at: 2.years.ago.., saved_annotation_id: nil).where("created_at != updated_at").count
```

**Comment by jorg-vr** [comment]
I my opinion we can justify the extra click for something that is only used in 10% of the cases
