### ISSUE TITLE
Wave pattern not always easily visible

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#4654]
This [submission](https://dodona.ugent.be/nl/courses/2263/series/24188/activities/30756865/) has a wave pattern below both the `i` and the  `j` characters on line 98. Because the character `j` hangs out of the line, the wave pattern is interrupted there, but as a result not a lot of it is visible anymore.

![image](https://github.com/dodona-edu/universal-judge/assets/5736113/787f2b4d-2365-4c0c-a221-390681478336)

Browser: Chrome (version 113.0.5672.93, 64-bits) on Windows 10

**Comment by bmesuere** [comment]
This is the default browser behaviour for text decoration in combination with descenders. It is possible to overwrite the default behaviour by using `text-decoration-skip-ink: none;`, but this might look ugly so it needs testing.

**Comment by jorg-vr** [comment]
this will slightly improve in #4846 
That pr uses `text-decoration-skip-ink: none;` but due to the layering it is rendered behind the text instead of above

It looks like this:
(Chrome)
![image](https://github.com/dodona-edu/dodona/assets/21177904/3ff04126-3db0-4eae-ba6b-2916c74afc79)
(Firefox)
![image](https://github.com/dodona-edu/dodona/assets/21177904/bc2a0cdf-1fe3-4f29-8041-9f7fea54b7a8)

**Comment by bmesuere** [comment]
For me, #4846 closes the issue. There's not much more we can do here.
