### ISSUE TITLE
Last character is missing in Python Tutor

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/dodona#5168]
While testing the [manual](https://docs.dodona.be/nl/guides/exercises/examples/input-output/#_4-een-testplan-maken) of this [exercise](https://github.com/dodona-edu/example-exercises/tree/master/tested/input-output/) I encountered this issue. The last character is missing in Python Tutor (see video).

https://github.com/dodona-edu/dodona/assets/56451049/422b6b6d-3dbb-4be5-8c21-f3bd619ae873

**Comment by pdawyndt** [comment]
While checking this issue, I also noticed the debugger is not available for the Python exercises from the course “De Programmeursleerling”.

**Comment by bmesuere** [comment]
@pdawyndt this is a know issue. We discussed it internally before. It is only the case for a small subset of "bad" exercises. We need some way to determine if we need to show the debugger button. Right now, if the judge provides additional test info we show the button. However, the programmeursleerling has some exercises where there are no test statements, no input and no files. The judge thus provides no additional info so we don't show the button. Since we can't fix this without modifying the output format and that these exercises are not up to our standard anyway, we decided to leave it as is.

**Comment by jorg-vr** [comment]
@niknetniko This is a partial TESTed issue.

For pythia exercises with input exercises we receive `"foo\nbar\n"`
For a similar tested input exercise we receive `"foo\nbar"`

I think the pythia format is preferable in this case, as the newline is required in a normal flow to trigger an input read.

The way dodona handles it is of course also not optimal. (The last character is removed and the tutor creates a list of lines by splitting on `\n`) But this can, and will probably, be changed in the future.
So I would still prefer the pythia format.

**Comment by jorg-vr** [comment]
@niknetniko is dit ondertussen opgelost in TESTed?

**Comment by niknetniko** [comment]
> @niknetniko is dit ondertussen opgelost in TESTed?

Het zou moeten, zie bijvoorbeeld https://dodona.be/nl/submissions/16583722.json. Als ik kijk staat daar een newline in bij stdin, maar de tutor toont ze nog steeds wel niet.
