### ISSUE TITLE
Code displayed differs from code submitted

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#5233]
This [feedback](https://dodona.be/nl/submissions/16357012/#code) does not show the same code that was submitted. See student question that describes the issue. Student could not reproduce this behaviour himself (personal communication).

**Comment by jorg-vr** [comment]
I cannot reproduce this either, how sure are we that the student did not by accident include that line?

Due to all the spaces, the extra text can be easily missed in the editor.
![Peek 2023-12-12 14-59](https://github.com/dodona-edu/dodona/assets/21177904/24c47e31-4e4c-4aee-83b4-257483c08e68)
This could lead the student to think it wasn't there while it was

**Comment by pdawyndt** [comment]
Not sure: if I resubmit the same code again, the extra clutter after the pathname in the hashbang line is there as well (falls off the screen, so not initially visible).

**Comment by jorg-vr** [comment]
Not a bug. Probably an oversight of the student.

**Comment by pdawyndt** [comment]
I asked the student for confirmation in Dodona (so you'll be able to see his answer there).

**Comment by pdawyndt** [comment]
Student has confirmed that he indeed submitted the code as observed. No Dodona issue altogether.
