### ISSUE TITLE
Incorrect exercise-amount displayed on course-page

### ISSUE THREAD

**Issue by BWindey** [dodona-edu/dodona#5347]
When viewing my subscribed courses, I noticed that a course of the new semester showed "66" in the column "Exercises" on https://dodona.be/courses?tab=my. This new course has no open exercises yet, so the amount of exercises should be shown as 0. 

On https://dodona.be/courses?tab=my:
![image](https://github.com/dodona-edu/dodona/assets/93756910/472daadf-5afe-4976-b6c5-27fc0b162fb8)

On the course-page:
![image](https://github.com/dodona-edu/dodona/assets/93756910/e54a5531-2a2d-48e6-b4e6-08fbd9437353)

**Comment by bmesuere** [comment]
The exercises are there, but aren't visible to you.

**Comment by BWindey** [comment]
So it's intended that the amount of exercises (hidden or not) is shown to students?

**Comment by bmesuere** [comment]
The exercise count is fetched from cache (https://github.com/dodona-edu/dodona/blob/main/app/models/course.rb#L324) and thus is the same for all users. Since these are shown on listing pages containing lots of courses, we can't query for the exact number taking into account the visibility per user. So this will be a "won't fix" I'm afraid.
