### ISSUE TITLE
Avoid unnecessary scrolling

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#5423]
The Python judge (not checked with other judges) has links to files used in test expressions. When clicking such a link, the file content is displayed in a popup window that is displayed near the top of the page:

![image](https://github.com/dodona-edu/dodona/assets/5736113/61aa9570-b7de-4bb4-8b5f-618540834cc9)

However, the rest of the page scrolls when clicking the file link, which is not needed (and annoying).

Example: https://dodona.be/nl/courses/3355/series/36011/activities/1108125720/

**Comment by BWindey** [comment]
Possibly related scrolling issues I encountered:
- When clicking the "Stijl" button without actually choosing a style, it scrolls to the top of the page, even if you're at the bottom. This also happens when you have navigated to an exercise-series by clicking the name in the right-menu (seen in the screenshot), actively removing part of the link (the part behind the # that points to the exercise-header-thing on the page).
This does not only occur on the courses-overview-page, but on all other pages I tried.
![image](https://github.com/dodona-edu/dodona/assets/93756910/2b5ac0fc-8415-49eb-88a6-40a91decb5c7)

- When loading a new page, and immediatly scrolling down while it's doing it's 2nd round of loading info, it scrolls right back up to the top when it finished loading that 2nd round. This is mostly noticeable for exercises with long descriptions (like those from prof. Dawyndt). Sometimes this doesn't happen, but instead just blocks you from scrolling.
[Screencast from 2024-04-23 22-54-17.webm](https://github.com/dodona-edu/dodona/assets/93756910/86e2684b-914f-4fe1-abe5-59eb09e15078)
In the video you see me scrolling down, and shortly after it scrolls back up by itself.

- Not sure if this one belongs here, but when you're on an exercise-page, and use the browsers Page-Back arrow (top left on Firefox), it doesn't return to the course-page, but scrolls back to the top of the exercise. I think this has to do with the exercise-description being loaded after the initial page loaded, so the link changes (it adds a # behind). 
[Screencast from 2024-04-23 22-58-53.webm](https://github.com/dodona-edu/dodona/assets/93756910/a5ca411b-dec8-4ecd-8034-da369ab4b769)
